version: '2'
services:
  web:
    build: ./web
    container_name: audioplayer
    ports:
      - "3000"
    volumes:
      - ./web/src/views:/var/app/views
    environment:
      - HOST=127.0.0.1
      - PORT=3000
            
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - web
    links:
      - web